spring.application.name=gestao-pedidos

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:lz45aEcKl+1fZPu4lIoJogPZzagGOI8Zn9gA6gS5A0w=}
jwt.expiration=3600000