package br.com.sergio.gestaopedidos.service;
import br.com.sergio.gestaopedidos.dto.compra.*;import br.com.sergio.gestaopedidos.entity.*;import br.com.sergio.gestaopedidos.enums.UnidadeMedida;import br.com.sergio.gestaopedidos.exception.*;import br.com.sergio.gestaopedidos.repository.CompraInsumoRepository;import org.junit.jupiter.api.Test;import org.springframework.data.domain.*;import java.lang.reflect.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import static org.assertj.core.api.Assertions.*;
class CompraInsumoServiceTest{
 static final LocalDate DATA=LocalDate.of(2026,8,3);
 @Test void cadastraUmItemCalculaCustoETotal(){Fake f=new Fake();f.insumos.put(1L,insumo(1,"Feijão",UnidadeMedida.QUILOGRAMA,true));var r=f.service().salvar(req(item(null,1,"25","210")));assertThat(r.valorTotal()).isEqualByComparingTo("210.00");assertThat(r.itens().getFirst().custoUnitario()).isEqualByComparingTo("8.400000");assertThat(r.itens().getFirst().unidadeMedida()).isEqualTo(UnidadeMedida.QUILOGRAMA);}
 @Test void cadastraVariosItensESomaTotalComArredondamento(){Fake f=new Fake();f.insumos.put(1L,insumo(1,"Feijão",UnidadeMedida.QUILOGRAMA,true));f.insumos.put(2L,insumo(2,"Embalagem",UnidadeMedida.UNIDADE,true));var r=f.service().salvar(req(item(null,1,"3","10"),item(null,2,"100","65")));assertThat(r.quantidadeItens()).isEqualTo(2);assertThat(r.valorTotal()).isEqualByComparingTo("75.00");assertThat(r.itens().getFirst().custoUnitario()).isEqualByComparingTo("3.333333");}
 @Test void rejeitaSemItensQuantidadeEValorInvalidos(){Fake f=new Fake();f.insumos.put(1L,insumo(1,"A",UnidadeMedida.QUILOGRAMA,true));assertThatThrownBy(()->f.service().salvar(req())).isInstanceOf(BusinessException.class);for(String q:List.of("0","-1"))assertThatThrownBy(()->f.service().salvar(req(item(null,1,q,"10")))).isInstanceOf(BusinessException.class);for(String v:List.of("0","-1"))assertThatThrownBy(()->f.service().salvar(req(item(null,1,"1",v)))).isInstanceOf(BusinessException.class);}
 @Test void rejeitaDuplicidadeInsumoInexistenteEInativo(){Fake f=new Fake();f.insumos.put(1L,insumo(1,"A",UnidadeMedida.QUILOGRAMA,true));f.insumos.put(2L,insumo(2,"B",UnidadeMedida.QUILOGRAMA,false));assertThatThrownBy(()->f.service().salvar(req(item(null,1,"1","2"),item(null,1,"2","3")))).hasMessage("Este insumo já foi adicionado à compra.");assertThatThrownBy(()->f.service().salvar(req(item(null,99,"1","2")))).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->f.service().salvar(req(item(null,2,"1","2")))).hasMessage("Este insumo não está disponível para novas compras.");}
 @Test void preservaItemHistoricoInativoEUnidadeHistorica(){Fake f=new Fake();Insumo i=insumo(1,"A",UnidadeMedida.GRAMA,false);f.insumos.put(1L,i);f.compra=compra(i,UnidadeMedida.QUILOGRAMA);var r=f.service().atualizar(10L,req(item(20L,1,"2","20")));assertThat(r.itens().getFirst().unidadeMedida()).isEqualTo(UnidadeMedida.QUILOGRAMA);assertThat(r.itens().getFirst().custoUnitario()).isEqualByComparingTo("10.000000");}
 @Test void editaCabecalhoIncluiRemoveERecalculaItens(){Fake f=new Fake();Insumo a=insumo(1,"A",UnidadeMedida.QUILOGRAMA,true),b=insumo(2,"B",UnidadeMedida.LITRO,true);f.insumos.put(1L,a);f.insumos.put(2L,b);f.compra=compra(a,UnidadeMedida.QUILOGRAMA);CompraInsumoRequest r=req(item(null,2,"2","30"));r.setFornecedor(" Novo ");var out=f.service().atualizar(10L,r);assertThat(out.fornecedor()).isEqualTo("Novo");assertThat(out.itens()).hasSize(1);assertThat(out.itens().getFirst().insumoId()).isEqualTo(2);assertThat(f.compra.getItens()).allMatch(x->Objects.equals(x.getInsumo().getId(),2L));}
 @Test void rejeitaIdDeItemDeOutraCompra(){Fake f=new Fake();Insumo a=insumo(1,"A",UnidadeMedida.QUILOGRAMA,true);f.insumos.put(1L,a);f.compra=compra(a,UnidadeMedida.QUILOGRAMA);assertThatThrownBy(()->f.service().atualizar(10L,req(item(999L,1,"1","1")))).hasMessage("Item informado não pertence a esta compra.");}
 @Test void excluiEPaginaComFiltros(){Fake f=new Fake();Insumo a=insumo(1,"A",UnidadeMedida.QUILOGRAMA,true);f.compra=compra(a,UnidadeMedida.QUILOGRAMA);f.resumo=true;var p=f.service().listar(DATA.minusDays(1),DATA.plusDays(1)," mercado ",PageRequest.of(0,10));assertThat(p).hasSize(1);assertThat(f.fornecedor).isEqualTo("mercado");f.service().excluir(10L);assertThat(f.excluiu).isTrue();}
 private CompraInsumoRequest req(ItemCompraInsumoRequest...itens){return CompraInsumoRequest.builder().dataCompra(DATA).fornecedor(" Mercado ").itens(new ArrayList<>(List.of(itens))).build();}private ItemCompraInsumoRequest item(Long id,long insumo,String q,String v){return ItemCompraInsumoRequest.builder().id(id).insumoId(insumo).quantidade(new BigDecimal(q)).valorTotalItem(new BigDecimal(v)).build();}
 private Insumo insumo(long id,String n,UnidadeMedida u,boolean ativo){return Insumo.builder().id(id).nome(n).unidadeMedida(u).ativo(ativo).build();}
 private CompraInsumo compra(Insumo i,UnidadeMedida u){CompraInsumo c=CompraInsumo.builder().id(10L).dataCompra(DATA).fornecedor("X").build();ItemCompraInsumo item=ItemCompraInsumo.builder().id(20L).insumo(i).unidadeMedida(u).quantidade(new BigDecimal("1.000")).valorTotalItem(new BigDecimal("10.00")).custoUnitario(new BigDecimal("10.000000")).build();c.adicionarItem(item);c.recalcularTotal();return c;}
 class Fake implements InvocationHandler{Map<Long,Insumo>insumos=new HashMap<>();CompraInsumo compra;boolean excluiu,resumo;String fornecedor;CompraInsumoRepository repo;
  CompraInsumoService service(){repo=(CompraInsumoRepository)Proxy.newProxyInstance(getClass().getClassLoader(),new Class[]{CompraInsumoRepository.class},this);InsumoService is=new InsumoService(null,null){@Override Insumo buscarEntidade(Long id){Insumo i=insumos.get(id);if(i==null)throw new ResourceNotFoundException("Insumo não encontrado.");return i;}};EstoqueService es=new EstoqueService(null,null,null){@Override public void processarCompra(CompraInsumo c){}@Override public boolean compraMovimentada(Long id){return false;}};return new CompraInsumoService(repo,is,es);}
  public Object invoke(Object p,Method m,Object[]a){return switch(m.getName()){case"save","saveAndFlush"->{compra=(CompraInsumo)a[0];if(compra.getId()==null)compra.setId(10L);long id=20;for(var i:compra.getItens())if(i.getId()==null)i.setId(id++);yield compra;}case"buscarDetalhada"->Optional.ofNullable(compra);case"delete"->{excluiu=true;yield null;}case"buscar"->{fornecedor=(String)a[2];Pageable pg=(Pageable)a[3];if(!resumo)yield Page.empty(pg);CompraInsumoRepository.Resumo r=(CompraInsumoRepository.Resumo)Proxy.newProxyInstance(getClass().getClassLoader(),new Class[]{CompraInsumoRepository.Resumo.class},(x,y,z)->switch(y.getName()){case"getId"->10L;case"getDataCompra"->DATA;case"getFornecedor"->"Mercado";case"getValorTotal"->new BigDecimal("10");case"getAtualizadoEm"->java.time.LocalDateTime.now();case"getQuantidadeItens"->1L;case"getStatus"->br.com.sergio.gestaopedidos.enums.StatusCompraInsumo.ATIVA;default->null;});yield new PageImpl<>(List.of(r),pg,1);}default->null;};}}
}
