package br.com.sergio.gestaopedidos.service;
import br.com.sergio.gestaopedidos.dto.compra.*;import br.com.sergio.gestaopedidos.entity.*;import br.com.sergio.gestaopedidos.enums.*;import br.com.sergio.gestaopedidos.exception.*;import br.com.sergio.gestaopedidos.repository.CompraRepository;import org.junit.jupiter.api.Test;import org.springframework.data.domain.*;import java.lang.reflect.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import static org.assertj.core.api.Assertions.*;
class CompraServiceTest{
 @Test void compraInsumoPreservaHistoricoCalculaCustoETotal(){Fake f=new Fake();f.insumos.put(1L,f.insumo(1,"Feijão",UnidadeMedida.QUILOGRAMA,true));var r=f.service().salvar(f.req(f.item(null,TipoItemEstoque.INSUMO,1,"25","210")));assertThat(r.tipoCompra()).isEqualTo(TipoCompra.INSUMO);assertThat(r.valorTotal()).isEqualByComparingTo("210.00");assertThat(r.itens().getFirst().nomeHistorico()).isEqualTo("Feijão");assertThat(r.itens().getFirst().unidadeHistorica()).isEqualTo(UnidadeMedida.QUILOGRAMA);assertThat(r.itens().getFirst().custoUnitario()).isEqualByComparingTo("8.400000");}
 @Test void validaTipoDuplicidadeInativoEUnidade(){Fake f=new Fake();f.insumos.put(1L,f.insumo(1,"A",UnidadeMedida.UNIDADE,true));f.insumos.put(2L,f.insumo(2,"B",UnidadeMedida.UNIDADE,false));assertThatThrownBy(()->f.service().salvar(f.req(f.item(null,null,1,"1","1")))).hasMessage("Selecione o item comprado.");assertThatThrownBy(()->f.service().salvar(f.req(f.item(null,TipoItemEstoque.INSUMO,1,"1","1"),f.item(null,TipoItemEstoque.INSUMO,1,"2","2")))).hasMessage("Este item já foi adicionado à compra.");assertThatThrownBy(()->f.service().salvar(f.req(f.item(null,TipoItemEstoque.INSUMO,2,"1","1")))).hasMessageContaining("não está disponível");assertThatThrownBy(()->f.service().salvar(f.req(f.item(null,TipoItemEstoque.INSUMO,1,"1.5","2")))).hasMessageContaining("inteira");}
 @Test void revendaAtivaGeraCompraComHistorico(){Fake f=new Fake();f.produtos.put(1L,Produto.builder().id(1L).nome("Refrigerante").tipoProduto(TipoProduto.PRODUTO_REVENDA).unidadeVenda(UnidadeVenda.UNIDADE).ativo(true).build());var r=f.service().salvar(f.req(f.item(null,TipoItemEstoque.PRODUTO_REVENDA,1,"2","10")));assertThat(r.tipoCompra()).isEqualTo(TipoCompra.PRODUTO_REVENDA);assertThat(r.itens().getFirst().nomeHistorico()).isEqualTo("Refrigerante");assertThat(r.itens().getFirst().unidadeHistorica()).isEqualTo(UnidadeMedida.UNIDADE);}
 @Test void compraMistaAceitaIdsIguaisEIdentificaCadaOrigem(){Fake f=new Fake();f.insumos.put(1L,f.insumo(1,"Feijão",UnidadeMedida.QUILOGRAMA,true));f.produtos.put(1L,Produto.builder().id(1L).nome("Frango").tipoProduto(TipoProduto.PRODUTO_REVENDA).unidadeVenda(UnidadeVenda.UNIDADE).ativo(true).build());var r=f.service().salvar(f.req(f.item(null,TipoItemEstoque.INSUMO,1,"2","20"),f.item(null,TipoItemEstoque.PRODUTO_REVENDA,1,"3","45")));assertThat(r.tipoCompra()).isEqualTo(TipoCompra.MISTA);assertThat(r.itens()).extracting(ItemCompraResponse::tipoItem).containsExactly(TipoItemEstoque.INSUMO,TipoItemEstoque.PRODUTO_REVENDA);assertThat(f.compra.getItens().get(0).getInsumo()).isNotNull();assertThat(f.compra.getItens().get(1).getProduto()).isNotNull();}
 @Test void compraMovimentadaPermiteSomenteEditarCabecalho(){Fake f=new Fake();Insumo i=f.insumo(1,"A",UnidadeMedida.QUILOGRAMA,true);f.insumos.put(1L,i);f.compra=f.compra(i);f.movimentada=true;CompraRequest alterada=f.req(f.item(20L,TipoItemEstoque.PRODUTO_REVENDA,1,"1","10"));assertThatThrownBy(()->f.service().atualizar(10L,alterada)).hasMessageContaining("Somente fornecedor e observação");CompraRequest r=f.req(f.item(20L,TipoItemEstoque.INSUMO,1,"1","10"));r.setFornecedor(" Novo ");assertThat(f.service().atualizar(10L,r).fornecedor()).isEqualTo("Novo");}
 @Test void compraIncompletaNaoEhPersistida(){Fake f=new Fake();assertThatThrownBy(()->f.service().salvar(f.req())).hasMessage("Adicione ao menos um item à compra.");assertThat(f.compra).isNull();}
 private static class Fake implements InvocationHandler{Map<Long,Insumo>insumos=new HashMap<>();Map<Long,Produto>produtos=new HashMap<>();Compra compra;CompraRepository repo;boolean movimentada;
  CompraService service(){repo=(CompraRepository)Proxy.newProxyInstance(getClass().getClassLoader(),new Class[]{CompraRepository.class},this);InsumoService is=new InsumoService(null,null){@Override Insumo buscarEntidade(Long id){Insumo i=insumos.get(id);if(i==null)throw new ResourceNotFoundException("Insumo não encontrado.");return i;}};ProdutoService ps=new ProdutoService(null,null,null){@Override public Produto buscarEntidadePorId(Long id){Produto p=produtos.get(id);if(p==null)throw new ResourceNotFoundException("Produto não encontrado.");return p;}};EstoqueService es=new EstoqueService(null,null,is,ps,null){@Override public void processarCompra(Compra c){}@Override public boolean compraMovimentada(Long id){return movimentada;}@Override public void estornarCompra(Compra c){c.setStatus(StatusCompra.ESTORNADA);}};return new CompraService(repo,is,ps,es);}
  public Object invoke(Object p,Method m,Object[]a){return switch(m.getName()){case"save","saveAndFlush"->{compra=(Compra)a[0];if(compra.getId()==null)compra.setId(10L);long id=20;for(ItemCompra i:compra.getItens())if(i.getId()==null)i.setId(id++);yield compra;}case"buscarDetalhada"->Optional.ofNullable(compra);default->null;};}
  CompraRequest req(ItemCompraRequest...itens){return CompraRequest.builder().dataCompra(LocalDate.of(2026,8,3)).fornecedor(" Mercado ").itens(new ArrayList<>(List.of(itens))).build();}ItemCompraRequest item(Long id,TipoItemEstoque tipo,long ref,String q,String v){return ItemCompraRequest.builder().id(id).tipoItem(tipo).referenciaId(ref).quantidade(new BigDecimal(q)).valorTotalItem(new BigDecimal(v)).build();}Insumo insumo(long id,String nome,UnidadeMedida u,boolean ativo){return Insumo.builder().id(id).nome(nome).unidadeMedida(u).ativo(ativo).build();}Compra compra(Insumo i){Compra c=Compra.builder().id(10L).tipoCompra(TipoCompra.INSUMO).dataCompra(LocalDate.of(2026,8,3)).status(StatusCompra.ATIVA).build();c.adicionarItem(ItemCompra.builder().id(20L).insumo(i).nomeHistorico(i.getNome()).unidadeHistorica(i.getUnidadeMedida()).quantidade(new BigDecimal("1.000")).valorTotalItem(new BigDecimal("10.00")).custoUnitario(new BigDecimal("10.000000")).build());c.recalcularTotal();return c;}}
}
