package br.com.sergio.gestaopedidos.service;
import br.com.sergio.gestaopedidos.dto.composicao.*;import br.com.sergio.gestaopedidos.entity.*;import br.com.sergio.gestaopedidos.enums.*;import br.com.sergio.gestaopedidos.repository.*;import org.junit.jupiter.api.*;import java.math.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
class ComposicaoProdutoServiceTest{
 ComposicaoProdutoRepository repo;ProdutoRepository produtos;InsumoRepository insumos;SaldoEstoqueRepository saldos;ComposicaoProdutoService service;Produto comercial,preparacao;Insumo insumo;
 @BeforeEach void setup(){repo=mock(ComposicaoProdutoRepository.class);produtos=mock(ProdutoRepository.class);insumos=mock(InsumoRepository.class);saldos=mock(SaldoEstoqueRepository.class);service=new ComposicaoProdutoService(repo,produtos,insumos,saldos);comercial=Produto.builder().id(1L).nome("Feijoada Média").tipoProduto(TipoProduto.PRODUTO_COMERCIAL).ativo(true).build();preparacao=Produto.builder().id(2L).nome("Feijoada pronta").tipoProduto(TipoProduto.PREPARACAO_PRODUZIDA).unidadeVenda(UnidadeVenda.QUILOGRAMA).ativo(true).build();insumo=Insumo.builder().id(3L).nome("Embalagem").unidadeMedida(UnidadeMedida.UNIDADE).ativo(true).build();when(produtos.findById(1L)).thenReturn(Optional.of(comercial));when(produtos.findById(2L)).thenReturn(Optional.of(preparacao));when(insumos.findById(3L)).thenReturn(Optional.of(insumo));}
 @Test void somenteProdutoComercialPodeTerComposicao(){comercial.setTipoProduto(TipoProduto.PRODUTO_REVENDA);assertThatThrownBy(()->service.salvar(request(item(TipoComponenteComposicao.INSUMO,3L,"1")))).hasMessageContaining("Produto de venda");}
 @Test void aceitaPreparacaoEInsumo(){ComposicaoProdutoRequest r=request(item(TipoComponenteComposicao.PREPARACAO_PRODUZIDA,2L,"0.500"),item(TipoComponenteComposicao.INSUMO,3L,"1"));java.util.concurrent.atomic.AtomicReference<ComposicaoProduto> salva=new java.util.concurrent.atomic.AtomicReference<>();when(repo.save(any())).thenAnswer(i->{ComposicaoProduto c=i.getArgument(0);c.setId(10L);salva.set(c);return c;});when(repo.buscarDetalhada(10L)).thenAnswer(i->Optional.of(salva.get()));assertThat(service.salvar(r).itens()).hasSize(2);}
 @Test void rejeitaDuplicidade(){assertThatThrownBy(()->service.salvar(request(item(TipoComponenteComposicao.INSUMO,3L,"1"),item(TipoComponenteComposicao.INSUMO,3L,"2")))).hasMessageContaining("repetido");}
 @Test void rejeitaQuantidadeInvalida(){assertThatThrownBy(()->service.salvar(request(item(TipoComponenteComposicao.INSUMO,3L,"0")))).hasMessageContaining("Quantidade");}
 @Test void custoEstimadoUsaCustoMedioAtual(){ComposicaoProduto c=ComposicaoProduto.builder().id(10L).produtoComercial(comercial).ativa(true).build();c.adicionarItem(ItemComposicaoProduto.builder().tipoComponente(TipoComponenteComposicao.PREPARACAO_PRODUZIDA).preparacao(preparacao).nomeHistorico(preparacao.getNome()).unidadeHistorica(UnidadeMedida.QUILOGRAMA).quantidade(new BigDecimal("0.500")).build());when(repo.buscarDetalhada(10L)).thenReturn(Optional.of(c));when(saldos.buscarSaldo(TipoItemEstoque.PREPARACAO_PRODUZIDA,2L)).thenReturn(Optional.of(SaldoEstoque.builder().custoMedioAtual(new BigDecimal("20.000000")).build()));assertThat(service.buscar(10L).custoEstimadoTotal()).isEqualByComparingTo("10.00");}
 @Test void atualizarMantemItemExistenteSemReinserirParUnico(){ItemComposicaoProduto existente=ItemComposicaoProduto.builder().id(1L).tipoComponente(TipoComponenteComposicao.PREPARACAO_PRODUZIDA).preparacao(preparacao).nomeHistorico(preparacao.getNome()).unidadeHistorica(UnidadeMedida.QUILOGRAMA).quantidade(new BigDecimal("0.500")).build();ComposicaoProduto c=ComposicaoProduto.builder().id(1L).produtoComercial(comercial).ativa(true).build();c.adicionarItem(existente);when(repo.buscarDetalhada(1L)).thenReturn(Optional.of(c));ItemComposicaoProdutoRequest enviado=item(TipoComponenteComposicao.PREPARACAO_PRODUZIDA,2L,"0.500");enviado.setId(1L);var resposta=service.atualizar(1L,request(enviado));assertThat(c.getItens()).containsExactly(existente);assertThat(c.getItens().getFirst().getId()).isEqualTo(1L);assertThat(resposta.itens().getFirst().unidade()).isEqualTo(UnidadeMedida.QUILOGRAMA);}
 @Test void componentesInsumoUsamTodosOsAtivosSemDependerDeSaldoOuCusto(){Insumo alho=Insumo.builder().id(4L).nome("Alho").unidadeMedida(UnidadeMedida.QUILOGRAMA).ativo(true).build();when(insumos.findByAtivoTrueAndNomeContainingIgnoreCaseOrderByNomeAsc("")).thenReturn(List.of(alho,insumo));when(saldos.buscarSaldo(TipoItemEstoque.INSUMO,4L)).thenReturn(Optional.empty());when(saldos.buscarSaldo(TipoItemEstoque.INSUMO,3L)).thenReturn(Optional.empty());var componentes=service.buscarComponentes(TipoComponenteComposicao.INSUMO,"");assertThat(componentes).extracting(ComponenteComposicaoResponse::nome).containsExactly("Alho","Embalagem");assertThat(componentes).extracting(ComponenteComposicaoResponse::custoMedio).allMatch(c->c.compareTo(BigDecimal.ZERO)==0);verify(insumos).findByAtivoTrueAndNomeContainingIgnoreCaseOrderByNomeAsc("");verify(insumos,never()).findTop20ByAtivoTrueAndNomeContainingIgnoreCaseOrderByNomeAsc(anyString());}
 @Test void preparacoesProduzidasMantemConsultaAtual(){when(produtos.findTop20ByTipoProdutoAndAtivoTrueAndNomeContainingIgnoreCaseOrderByNomeAsc(TipoProduto.PREPARACAO_PRODUZIDA,"feijoada")).thenReturn(List.of(preparacao));when(saldos.buscarSaldo(TipoItemEstoque.PREPARACAO_PRODUZIDA,2L)).thenReturn(Optional.empty());assertThat(service.buscarComponentes(TipoComponenteComposicao.PREPARACAO_PRODUZIDA," feijoada ")).extracting(ComponenteComposicaoResponse::nome).containsExactly("Feijoada pronta");}
 private ComposicaoProdutoRequest request(ItemComposicaoProdutoRequest...itens){return ComposicaoProdutoRequest.builder().produtoComercialId(1L).ativa(true).itens(List.of(itens)).build();}private ItemComposicaoProdutoRequest item(TipoComponenteComposicao t,long id,String q){return ItemComposicaoProdutoRequest.builder().tipoComponente(t).referenciaId(id).quantidade(new BigDecimal(q)).build();}
}
