package br.com.sergio.gestaopedidos.service;
import br.com.sergio.gestaopedidos.dto.estoque.*;import br.com.sergio.gestaopedidos.entity.*;import br.com.sergio.gestaopedidos.enums.*;import br.com.sergio.gestaopedidos.repository.*;import org.junit.jupiter.api.Test;import java.lang.reflect.Proxy;import java.math.BigDecimal;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;
class EstoqueServiceTest{
 @Test void custoMedioSaidaEEstornoDaCompra(){Fake f=new Fake(UnidadeMedida.QUILOGRAMA,true);EstoqueService s=f.service();s.registrarEntradaManual(f.entrada("10","100"));s.registrarEntradaManual(f.entrada("10","200"));assertThat(f.saldo.getCustoMedioAtual()).isEqualByComparingTo("15.000000");s.registrarSaidaManual(f.saida("5"));assertThat(f.saldo.getQuantidadeAtual()).isEqualByComparingTo("15.000");assertThat(f.saldo.getValorTotalEstoque()).isEqualByComparingTo("225.00");Fake g=new Fake(UnidadeMedida.QUILOGRAMA,true);Compra c=g.compra("4","40");g.service().processarCompra(c);g.service().processarCompra(c);assertThat(g.movimentos).hasSize(1);g.service().estornarCompra(c);assertThat(c.getStatus()).isEqualTo(StatusCompra.ESTORNADA);assertThat(g.saldo.getQuantidadeAtual()).isZero();}
 @Test void validaSaldoAtivoEUnidade(){Fake f=new Fake(UnidadeMedida.UNIDADE,true);EstoqueService s=f.service();s.registrarEntradaManual(f.entrada("2","20"));assertThatThrownBy(()->s.registrarSaidaManual(f.saida("3"))).hasMessageContaining("Estoque insuficiente");assertThatThrownBy(()->s.registrarEntradaManual(f.entrada("1.5","10"))).hasMessageContaining("inteira");f.insumo.setAtivo(false);assertThatThrownBy(()->s.registrarEntradaManual(f.entrada("1","10"))).hasMessageContaining("não está disponível");}
 static class Fake{final Insumo insumo;EstoqueInsumo saldo;final List<MovimentacaoEstoque>movimentos=new ArrayList<>();long seq=1;Fake(UnidadeMedida u,boolean ativo){insumo=Insumo.builder().id(1L).nome("Feijão").unidadeMedida(u).ativo(ativo).estoqueMinimo(BigDecimal.ZERO).build();}
  EstoqueService service(){EstoqueInsumoRepository er=(EstoqueInsumoRepository)Proxy.newProxyInstance(getClass().getClassLoader(),new Class[]{EstoqueInsumoRepository.class},(p,m,a)->switch(m.getName()){case"bloquearInsumo","buscarInsumo"->Optional.of(insumo);case"findByInsumoId","buscarSaldo"->Optional.ofNullable(saldo);case"save"->{saldo=(EstoqueInsumo)a[0];yield saldo;}default->zero(m.getReturnType());});MovimentacaoEstoqueRepository mr=(MovimentacaoEstoqueRepository)Proxy.newProxyInstance(getClass().getClassLoader(),new Class[]{MovimentacaoEstoqueRepository.class},(p,m,a)->switch(m.getName()){case"existsByItemCompraIdAndTipo"->movimentos.stream().anyMatch(x->x.getItemCompra()!=null&&Objects.equals(x.getItemCompra().getId(),a[0])&&x.getTipo()==a[1]);case"save"->{MovimentacaoEstoque x=(MovimentacaoEstoque)a[0];x.setId(seq++);movimentos.add(x);yield x;}case"findByItemCompraCompraIdAndTipoOrderByIdAsc"->movimentos.stream().filter(x->x.getItemCompra()!=null&&Objects.equals(x.getItemCompra().getCompra().getId(),a[0])&&x.getTipo()==a[1]).toList();default->zero(m.getReturnType());});return new EstoqueService(er,mr);}
  EntradaEstoqueRequest entrada(String q,String v){return EntradaEstoqueRequest.builder().insumoId(1L).quantidade(new BigDecimal(q)).valorTotal(new BigDecimal(v)).dataMovimentacao(LocalDateTime.now()).build();}SaidaEstoqueRequest saida(String q){return SaidaEstoqueRequest.builder().insumoId(1L).quantidade(new BigDecimal(q)).tipo(TipoMovimentacaoEstoque.SAIDA_CONSUMO_MANUAL).dataMovimentacao(LocalDateTime.now()).build();}
  Compra compra(String q,String v){Compra c=Compra.builder().id(7L).tipoCompra(TipoCompra.INSUMO).dataCompra(LocalDate.now()).status(StatusCompra.ATIVA).build();ItemCompra i=ItemCompra.builder().id(9L).insumo(insumo).nomeHistorico(insumo.getNome()).unidadeHistorica(insumo.getUnidadeMedida()).quantidade(new BigDecimal(q)).valorTotalItem(new BigDecimal(v)).custoUnitario(new BigDecimal(v).divide(new BigDecimal(q),6,java.math.RoundingMode.HALF_UP)).build();c.adicionarItem(i);return c;}static Object zero(Class<?>t){if(t==boolean.class)return false;if(t==long.class)return 0L;if(t==int.class)return 0;if(Optional.class.isAssignableFrom(t))return Optional.empty();return null;}}
}
