package br.com.sergio.gestaopedidos.service;

import br.com.sergio.gestaopedidos.dto.pedido.*;import br.com.sergio.gestaopedidos.entity.*;import br.com.sergio.gestaopedidos.enums.*;import br.com.sergio.gestaopedidos.exception.BusinessException;import br.com.sergio.gestaopedidos.mapper.PedidoMapper;import br.com.sergio.gestaopedidos.repository.*;import org.junit.jupiter.api.Test;
import java.lang.reflect.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import static org.assertj.core.api.Assertions.*;

class PedidoServiceProdutoVendaTest {
    @Test void deveRejeitarProdutoAtivoNaoVendavel(){assertIndisponivel(produto(true,false));}
    @Test void deveRejeitarProdutoInativoMesmoVendavel(){assertIndisponivel(produto(false,true));}
    @Test void pedidoHistoricoContinuaConsultavelComProdutoIndisponivel(){Fake f=new Fake(produto(false,false));f.historico=Pedido.builder().id(9L).cliente(cliente()).itens(new ArrayList<>()).build();assertThatCode(()->f.service().buscarPorId(9L)).doesNotThrowAnyException();}
    @Test void transicaoParaPreparacaoNaoMovimentaEstoque(){Fake f=new Fake(produto(true,true));f.historico=pedido(StatusPedido.PENDENTE,false,BigDecimal.ONE);f.service().alterarStatus(9L,StatusPedido.EM_PREPARACAO,null);assertThat(f.processamentos).isZero();assertThat(f.historico.getEstoqueMovimentado()).isFalse();assertThat(f.historico.getStatus()).isEqualTo(StatusPedido.EM_PREPARACAO);}
    @Test void transicaoParaProntoMovimentaEstoqueComQuantidadeFinal(){Fake f=new Fake(produto(true,true));f.historico=pedido(StatusPedido.EM_PREPARACAO,false,new BigDecimal("1.290"));f.service().alterarStatus(9L,StatusPedido.PRONTO,null);assertThat(f.processamentos).isOne();assertThat(f.quantidadeProcessada).isEqualByComparingTo("1.290");assertThat(f.historico.getStatus()).isEqualTo(StatusPedido.PRONTO);}
    @Test void pedidoLegadoEmPreparacaoJaMovimentadoNaoBaixaNovamente(){Fake f=new Fake(produto(true,true));f.historico=pedido(StatusPedido.EM_PREPARACAO,true,BigDecimal.ONE);f.service().alterarStatus(9L,StatusPedido.PRONTO,null);assertThat(f.processamentos).isOne();assertThat(f.baixasEfetivas).isZero();assertThat(f.historico.getStatus()).isEqualTo(StatusPedido.PRONTO);}
    @Test void pedidoLegadoProntoNaoPossuiNovaTransicaoParaPronto(){Fake f=new Fake(produto(true,true));f.historico=pedido(StatusPedido.PRONTO,true,BigDecimal.ONE);assertThatThrownBy(()->f.service().alterarStatus(9L,StatusPedido.PRONTO,null)).isInstanceOf(BusinessException.class);assertThat(f.processamentos).isZero();}
    @Test void pedidoLegadoProntoAvancaSemNovaBaixa(){Fake f=new Fake(produto(true,true));f.historico=pedido(StatusPedido.PRONTO,true,BigDecimal.ONE);f.service().alterarStatus(9L,StatusPedido.ENTREGUE,null);assertThat(f.processamentos).isZero();assertThat(f.historico.getStatus()).isEqualTo(StatusPedido.ENTREGUE);}
    @Test void falhaNaBaixaImpedeStatusPronto(){Fake f=new Fake(produto(true,true));f.historico=pedido(StatusPedido.EM_PREPARACAO,false,BigDecimal.ONE);f.falharProcessamento=true;assertThatThrownBy(()->f.service().alterarStatus(9L,StatusPedido.PRONTO,null)).isInstanceOf(BusinessException.class);assertThat(f.historico.getStatus()).isEqualTo(StatusPedido.EM_PREPARACAO);assertThat(f.historico.getEstoqueMovimentado()).isFalse();}
    @Test void cancelamentoAntesDeProntoNaoEstorna(){Fake f=new Fake(produto(true,true));f.historico=pedido(StatusPedido.EM_PREPARACAO,false,BigDecimal.ONE);f.service().alterarStatus(9L,StatusPedido.CANCELADO,"Cliente desistiu");assertThat(f.estornosEfetivos).isZero();assertThat(f.historico.getStatus()).isEqualTo(StatusPedido.CANCELADO);}
    @Test void cancelamentoEstornaPedidoMovimentado(){Fake f=new Fake(produto(true,true));f.historico=pedido(StatusPedido.EM_PREPARACAO,true,BigDecimal.ONE);f.service().alterarStatus(9L,StatusPedido.CANCELADO,"Cliente desistiu");assertThat(f.movimentou).isTrue();assertThat(f.historico.getEstoqueMovimentado()).isFalse();assertThat(f.historico.getStatus()).isEqualTo(StatusPedido.CANCELADO);}
    @Test void pedidoMovimentadoEstornaEditaEAplicaNovamente(){Fake f=new Fake(produto(true,true));f.historico=pedido(StatusPedido.EM_PREPARACAO,true,BigDecimal.ONE);PedidoRequest alterado=PedidoRequest.builder().clienteId(1L).dataAgendada(LocalDate.now()).formaPagamento(FormaPagamento.PIX).tipoEntrega(TipoEntrega.RETIRADA).itens(List.of(ItemPedidoRequest.builder().produtoId(2L).quantidade(new BigDecimal("2")).build())).build();assertThatCode(()->f.service().atualizar(9L,alterado,List.of(5L))).doesNotThrowAnyException();assertThat(f.movimentou).isTrue();assertThat(f.historico.getItens().getFirst().getQuantidade()).isEqualByComparingTo("2");}
    @Test void pedidoEmPreparacaoSemBaixaPermiteCorrigirPesoSemEstorno(){Produto porPeso=produto(true,true);porPeso.setUnidadeVenda(UnidadeVenda.QUILOGRAMA);Fake f=new Fake(porPeso);f.historico=pedido(StatusPedido.EM_PREPARACAO,false,new BigDecimal("1.000"));f.historico.getItens().getFirst().setProduto(porPeso);PedidoRequest alterado=PedidoRequest.builder().clienteId(1L).dataAgendada(LocalDate.now()).formaPagamento(FormaPagamento.PIX).tipoEntrega(TipoEntrega.RETIRADA).itens(List.of(ItemPedidoRequest.builder().produtoId(2L).quantidade(new BigDecimal("1.290")).build())).build();f.service().atualizar(9L,alterado,List.of(5L));assertThat(f.processamentos).isZero();assertThat(f.estornosEfetivos).isZero();assertThat(f.historico.getItens().getFirst().getQuantidade()).isEqualByComparingTo("1.290");}
    @Test void situacaoEstoqueDistinguePreparacaoProntoELegado(){Fake f=new Fake(produto(true,true));PedidoService s=f.service();assertThat(s.situacaoEstoque(PedidoResponse.builder().id(1L).status(StatusPedido.PENDENTE).estoqueMovimentado(false).build())).isEqualTo("Aguardando baixa");assertThat(s.situacaoEstoque(PedidoResponse.builder().id(2L).status(StatusPedido.EM_PREPARACAO).estoqueMovimentado(false).build())).isEqualTo("Aguardando confirmação");assertThat(s.situacaoEstoque(PedidoResponse.builder().id(3L).status(StatusPedido.PRONTO).estoqueMovimentado(true).build())).isEqualTo("Estoque baixado");assertThat(s.situacaoEstoque(PedidoResponse.builder().id(4L).status(StatusPedido.EM_PREPARACAO).estoqueMovimentado(true).build())).isEqualTo("Estoque baixado");}
    @Test void retiradaZeraTaxaNoBackend(){Fake f=new Fake(produto(true,true));PedidoRequest r=PedidoRequest.builder().clienteId(1L).dataAgendada(LocalDate.now()).formaPagamento(FormaPagamento.PIX).tipoEntrega(TipoEntrega.RETIRADA).taxaEntrega(new BigDecimal("25.00")).itens(List.of(ItemPedidoRequest.builder().produtoId(2L).quantidade(BigDecimal.ONE).build())).build();f.service().salvar(r);assertThat(f.salvoPedido.getTaxaEntrega()).isEqualByComparingTo("0.00");assertThat(f.salvoPedido.getValorTotal()).isEqualByComparingTo("10.00");}
    private void assertIndisponivel(Produto p){Fake f=new Fake(p);assertThatThrownBy(()->f.service().salvar(request())).isInstanceOf(BusinessException.class).hasMessage("Este produto não está disponível para venda.");assertThat(f.salvou).isFalse();}
    private Cliente cliente(){return Cliente.builder().id(1L).nome("Cliente").telefone("1").build();}
    private Produto produto(boolean ativo,boolean vendavel){return Produto.builder().id(2L).nome("Produto").preco(BigDecimal.TEN).ativo(ativo).vendavel(vendavel).tipoProduto(TipoProduto.PRODUTO_REVENDA).unidadeVenda(UnidadeVenda.UNIDADE).permiteAcompanhamento(false).build();}
    private PedidoRequest request(){return PedidoRequest.builder().clienteId(1L).dataAgendada(LocalDate.now()).formaPagamento(FormaPagamento.PIX).tipoEntrega(TipoEntrega.RETIRADA).taxaEntrega(BigDecimal.ZERO).itens(List.of(ItemPedidoRequest.builder().produtoId(2L).quantidade(BigDecimal.ONE).build())).build();}
    private Pedido pedido(StatusPedido status,boolean movimentado,BigDecimal quantidade){ItemPedido item=ItemPedido.builder().id(5L).produto(produto(true,true)).quantidade(quantidade).precoUnitario(BigDecimal.TEN).subtotal(BigDecimal.TEN.multiply(quantidade)).build();return Pedido.builder().id(9L).cliente(cliente()).dataAgendada(LocalDate.now()).status(status).formaPagamento(FormaPagamento.PIX).tipoEntrega(TipoEntrega.RETIRADA).taxaEntrega(BigDecimal.ZERO).subtotal(item.getSubtotal()).estoqueMovimentado(movimentado).itens(new ArrayList<>(List.of(item))).build();}
    private class Fake implements InvocationHandler {Produto produto;Pedido historico,salvoPedido;boolean salvou,movimentou,falharProcessamento;int processamentos,baixasEfetivas,estornosEfetivos;BigDecimal quantidadeProcessada;ClienteRepository clientesProxy;ProdutoRepository produtosProxy;PedidoRepository pedidosProxy;Fake(Produto p){produto=p;}PedidoService service(){ClassLoader c=getClass().getClassLoader();pedidosProxy=(PedidoRepository)Proxy.newProxyInstance(c,new Class[]{PedidoRepository.class},this);clientesProxy=(ClienteRepository)Proxy.newProxyInstance(c,new Class[]{ClienteRepository.class},this);produtosProxy=(ProdutoRepository)Proxy.newProxyInstance(c,new Class[]{ProdutoRepository.class},this);EstoqueService estoque=new EstoqueService(null,null,null,null,null){@Override public void processarPedido(Pedido pedido){movimentou=true;processamentos++;quantidadeProcessada=pedido.getItens().getFirst().getQuantidade();if(falharProcessamento)throw new BusinessException("Estoque insuficiente");if(Boolean.TRUE.equals(pedido.getEstoqueMovimentado()))return;baixasEfetivas++;pedido.setEstoqueMovimentado(true);}@Override public void estornarPedido(Pedido pedido){movimentou=true;if(!Boolean.TRUE.equals(pedido.getEstoqueMovimentado()))return;estornosEfetivos++;pedido.setEstoqueMovimentado(false);}};return new PedidoService(pedidosProxy,clientesProxy,produtosProxy,(PedidoMapper)Proxy.newProxyInstance(c,new Class[]{PedidoMapper.class},this),estoque,(MovimentacaoEstoqueRepository)Proxy.newProxyInstance(c,new Class[]{MovimentacaoEstoqueRepository.class},this));}
        public Object invoke(Object p,Method m,Object[] a){return switch(m.getName()){case"findById"->p==clientesProxy?Optional.of(cliente()):p==produtosProxy?Optional.of(produto):Optional.ofNullable(historico);case"buscarDetalhado","bloquearDetalhado"->Optional.ofNullable(historico);case"save"->{salvou=true;salvoPedido=(Pedido)a[0];yield a[0];}case"toResponse"->null;default->null;};}}
}
