package br.com.sergio.gestaopedidos.service;
import br.com.sergio.gestaopedidos.dto.producao.*;import br.com.sergio.gestaopedidos.entity.*;import br.com.sergio.gestaopedidos.enums.*;import br.com.sergio.gestaopedidos.exception.BusinessException;import br.com.sergio.gestaopedidos.repository.*;import org.junit.jupiter.api.*;import java.math.*;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class ProducaoServiceTest{
 ProducaoRepository producoes;ProdutoRepository produtos;FichaTecnicaRepository fichas;MovimentacaoEstoqueRepository movimentos;SaldoEstoqueRepository saldos;EstoqueService estoque;ProducaoService service;Produto preparacao;FichaTecnica ficha;Insumo insumo;
 @BeforeEach void setup(){producoes=mock(ProducaoRepository.class);produtos=mock(ProdutoRepository.class);fichas=mock(FichaTecnicaRepository.class);movimentos=mock(MovimentacaoEstoqueRepository.class);saldos=mock(SaldoEstoqueRepository.class);estoque=mock(EstoqueService.class);service=new ProducaoService(producoes,produtos,fichas,movimentos,saldos,estoque);preparacao=Produto.builder().id(1L).nome("Feijoada pronta").tipoProduto(TipoProduto.PREPARACAO_PRODUZIDA).ativo(true).unidadeVenda(UnidadeVenda.QUILOGRAMA).build();insumo=Insumo.builder().id(2L).nome("Feijão").ativo(true).unidadeMedida(UnidadeMedida.QUILOGRAMA).build();ficha=FichaTecnica.builder().id(3L).produto(preparacao).ativa(true).build();ficha.adicionarItem(ItemFichaTecnica.builder().insumo(insumo).quantidade(new BigDecimal("0.400")).unidadeHistorica(UnidadeMedida.QUILOGRAMA).nomeHistorico("Feijão").build());when(produtos.findById(1L)).thenReturn(Optional.of(preparacao));when(fichas.findByProdutoId(1L)).thenReturn(Optional.of(ficha));when(fichas.buscarAtivasPorProdutos(anyCollection())).thenReturn(List.of(ficha));when(producoes.saveAndFlush(any())).thenAnswer(i->i.getArgument(0));}
 @Test void seletorRetornaPreparacaoMesmoSemConsultarSaldo(){when(produtos.buscarProduzidosAtivosComFichaAtiva()).thenReturn(List.of(preparacao));assertThat(service.produtosDisponiveis()).containsExactly(preparacao);verifyNoInteractions(saldos);}
 @Test void comercialNaoPodeSerProduzido(){preparacao.setTipoProduto(TipoProduto.PRODUTO_COMERCIAL);assertThatThrownBy(()->service.salvar(request())).hasMessageContaining("Somente preparações");}
 @Test void ausenciaDeFichaRejeitaRascunho(){when(fichas.findByProdutoId(1L)).thenReturn(Optional.empty());assertThatThrownBy(()->service.salvar(request())).hasMessageContaining("Ficha Técnica");}
 @Test void rascunhoNaoMovimentaEstoque(){service.salvar(request());verifyNoInteractions(estoque);}
 @Test void confirmacaoCalculaCustoTotalECustoPorKg(){Producao p=entidade();when(producoes.bloquearDetalhada(9L)).thenReturn(Optional.of(p));when(estoque.processarProducao(eq(p),anyMap(),eq(new BigDecimal("15.00")))).thenReturn(new BigDecimal("100.00"));service.confirmar(9L);assertThat(p.getStatus()).isEqualTo(StatusProducao.CONFIRMADA);assertThat(p.getValorInsumosConsumidos()).isEqualByComparingTo("100.00");assertThat(p.getCustoTotal()).isEqualByComparingTo("115.00");}
 @Test void confirmacaoDuplicadaBloqueada(){Producao p=entidade();p.setStatus(StatusProducao.CONFIRMADA);when(producoes.bloquearDetalhada(9L)).thenReturn(Optional.of(p));assertThatThrownBy(()->service.confirmar(9L)).hasMessageContaining("confirmada");verifyNoInteractions(estoque);}
 private ProducaoRequest request(){return ProducaoRequest.builder().dataProducao(LocalDate.now()).valorGasEnergia(new BigDecimal("10")).valorOutros(new BigDecimal("5")).itens(List.of(ItemProducaoRequest.builder().produtoId(1L).quantidade(new BigDecimal("35.500")).build())).build();}
 private Producao entidade(){Producao p=Producao.builder().id(9L).dataProducao(LocalDate.now()).status(StatusProducao.RASCUNHO).valorGasEnergia(new BigDecimal("10")).valorOutros(new BigDecimal("5")).build();p.adicionarItem(ItemProducao.builder().produto(preparacao).nomeHistorico(preparacao.getNome()).unidadeHistorica(UnidadeMedida.QUILOGRAMA).quantidade(new BigDecimal("35.500")).build());return p;}
}
