package br.com.sergio.gestaopedidos.service;
import br.com.sergio.gestaopedidos.dto.produto.*;import br.com.sergio.gestaopedidos.entity.Produto;import br.com.sergio.gestaopedidos.enums.*;import br.com.sergio.gestaopedidos.exception.BusinessException;import br.com.sergio.gestaopedidos.mapper.ProdutoMapper;import br.com.sergio.gestaopedidos.repository.ProdutoRepository;import org.junit.jupiter.api.*;import java.math.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
class ProdutoServiceTest{
 ProdutoRepository repo;ProdutoMapper mapper;ProdutoService service;
 @BeforeEach void setup(){repo=mock(ProdutoRepository.class);mapper=mock(ProdutoMapper.class);service=new ProdutoService(repo,mapper,null);when(repo.existsByNomeIgnoreCase(anyString())).thenReturn(false);when(repo.save(any())).thenAnswer(i->i.getArgument(0));when(mapper.toEntity(any())).thenAnswer(i->{ProdutoRequest r=i.getArgument(0);return Produto.builder().nome(r.nome()).build();});when(mapper.toResponse(any())).thenAnswer(i->resposta(i.getArgument(0)));}
 @Test void preparacaoPodeSerSalvaSemPrecoENaoVendavelEmKg(){ProdutoResponse r=service.salvar(request(TipoProduto.PREPARACAO_PRODUZIDA,null,true,UnidadeVenda.QUILOGRAMA));assertThat(r.preco()).isNull();assertThat(r.vendavel()).isFalse();assertThat(r.unidadeVenda()).isEqualTo(UnidadeVenda.QUILOGRAMA);assertThat(r.permiteAcompanhamento()).isFalse();}
 @Test void comercialExigePreco(){assertThatThrownBy(()->service.salvar(request(TipoProduto.PRODUTO_COMERCIAL,null,true,UnidadeVenda.UNIDADE))).isInstanceOf(BusinessException.class).hasMessageContaining("Preço");}
 @Test void comercialPodeSerVendavel(){assertThat(service.salvar(request(TipoProduto.PRODUTO_COMERCIAL,new BigDecimal("35"),true,UnidadeVenda.UNIDADE)).vendavel()).isTrue();}
 @Test void revendaExigePreco(){assertThatThrownBy(()->service.salvar(request(TipoProduto.PRODUTO_REVENDA,BigDecimal.ZERO,true,UnidadeVenda.UNIDADE))).hasMessageContaining("Preço");}
 @Test void buscaPedidoUsaSomenteComercialERevenda(){Produto p=Produto.builder().tipoProduto(TipoProduto.PRODUTO_COMERCIAL).build();when(repo.buscarVendaveis(anyCollection(),eq("fei"),any())).thenReturn(List.of(p));service.buscarAtivosEVendaveisPorNome(" fei ");verify(repo).buscarVendaveis(eq(EnumSet.of(TipoProduto.PRODUTO_COMERCIAL,TipoProduto.PRODUTO_REVENDA)),eq("fei"),any());}
 @Test void buscaCompraUsaSomenteRevendaAtiva(){service.buscarRevendaAtivosPorNome(" fra ");verify(repo).findTop20ByTipoProdutoAndAtivoTrueAndNomeContainingIgnoreCaseOrderByNomeAsc(TipoProduto.PRODUTO_REVENDA,"fra");}
 private ProdutoRequest request(TipoProduto t,BigDecimal preco,boolean vendavel,UnidadeVenda u){return ProdutoRequest.builder().nome("Feijoada").preco(preco).ativo(true).unidadeVenda(u).permiteAcompanhamento(true).tipoProduto(t).vendavel(vendavel).estoqueMinimo(BigDecimal.ZERO).build();}
 private ProdutoResponse resposta(Produto p){return ProdutoResponse.builder().id(p.getId()).nome(p.getNome()).preco(p.getPreco()).ativo(p.getAtivo()).vendavel(p.getVendavel()).tipoProduto(p.getTipoProduto()).unidadeVenda(p.getUnidadeVenda()).permiteAcompanhamento(p.getPermiteAcompanhamento()).estoqueMinimo(p.getEstoqueMinimo()).build();}
}
