package br.com.sergio.gestaopedidos.service;

import br.com.sergio.gestaopedidos.dto.producao.*;import br.com.sergio.gestaopedidos.entity.Producao;import br.com.sergio.gestaopedidos.enums.StatusPedido;import br.com.sergio.gestaopedidos.exception.BusinessException;import br.com.sergio.gestaopedidos.repository.*;import org.junit.jupiter.api.Test;import org.springframework.data.domain.*;
import java.lang.reflect.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import static org.assertj.core.api.Assertions.*;

class ProducaoServiceTest {
    private static final LocalDate DATA=LocalDate.of(2026,8,8);
    @Test void deveCadastrarNormalizarNulosESomarGastos(){Fake f=new Fake();var s=f.service().salvar(new ProducaoRequest(DATA,bd("100"),null,bd("20"),null," teste "));assertThat(s.totalGasto()).isEqualByComparingTo("120.00");assertThat(s.valorEmbalagens()).isEqualByComparingTo("0.00");assertThat(s.observacao()).isEqualTo("teste");}
    @Test void deveBloquearDuplicidadeNoCadastroENaAlteracaoMasPermitirPropriaData(){Fake f=new Fake();f.duplicada=true;assertThatThrownBy(()->f.service().salvar(request(DATA,"1"))).isInstanceOf(BusinessException.class);f.duplicada=false;f.entidade=entidade(1L,DATA,"1");assertThatCode(()->f.service().atualizar(1L,request(DATA,"2"))).doesNotThrowAnyException();f.duplicadaAtualizacao=true;assertThatThrownBy(()->f.service().atualizar(1L,request(DATA.plusDays(1),"2"))).isInstanceOf(BusinessException.class);}
    @Test void deveCalcularPedidosProdutosTaxasFaturamentoResultadoPositivoEMargem(){Fake f=new Fake();f.entidade=entidade(1L,DATA,"150");f.financeiro=financeiro(DATA,3,"270","30","300");var r=f.service().buscarResumoPorId(1L);assertThat(r.pedidosValidos()).isEqualTo(3);assertThat(r.faturamentoProdutos()).isEqualByComparingTo("270");assertThat(r.taxasEntrega()).isEqualByComparingTo("30");assertThat(r.resultadoBrutoEstimado()).isEqualByComparingTo("150.00");assertThat(r.margemBrutaEstimada()).isEqualByComparingTo("50.00");}
    @Test void deveCalcularResultadoNegativoZeradoEFaturamentoZero(){Fake f=new Fake();f.entidade=entidade(1L,DATA,"100");f.financeiro=financeiro(DATA,1,"40","10","50");assertThat(f.service().buscarResumoPorId(1L).resultadoBrutoEstimado()).isEqualByComparingTo("-50.00");f.entidade.setValorIngredientes(bd("50"));assertThat(f.service().buscarResumoPorId(1L).resultadoBrutoEstimado()).isZero();f.financeiro=null;var v=f.service().buscarResumoPorId(1L);assertThat(v.margemBrutaEstimada()).isZero();assertThat(v.resultadoBrutoEstimado()).isEqualByComparingTo("-50.00");}
    @Test void devePaginarFiltrarAgregarEmLoteEExcluirSemAlterarPedidos(){Fake f=new Fake();f.entidade=entidade(1L,DATA,"4");f.financeiro=financeiro(DATA,1,"10","2","12");f.total=15;var page=PageRequest.of(1,10,Sort.by("dataProducao"));var r=f.service().listar(DATA.minusDays(7),DATA,page);assertThat(r.getNumber()).isEqualTo(1);assertThat(r.getTotalElements()).isEqualTo(11);assertThat(r.getContent().getFirst().faturamentoTotal()).isEqualByComparingTo("12.00");f.service().excluir(1L);assertThat(f.excluiuProducao).isTrue();assertThat(f.alterouPedido).isFalse();}
    private ProducaoRequest request(LocalDate d,String total){return new ProducaoRequest(d,bd(total),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,null);}private static BigDecimal bd(String v){return new BigDecimal(v);}private Producao entidade(Long id,LocalDate d,String total){return Producao.builder().id(id).dataProducao(d).valorIngredientes(bd(total)).valorEmbalagens(BigDecimal.ZERO).valorGasEnergia(BigDecimal.ZERO).valorOutros(BigDecimal.ZERO).build();}
    private PedidoRepository.ResumoFinanceiroProducao financeiro(LocalDate d,long q,String p,String t,String total){Map<String,Object> m=Map.of("getDataProducao",d,"getPedidosValidos",q,"getFaturamentoProdutos",bd(p),"getTaxasEntrega",bd(t),"getFaturamentoTotal",bd(total));return (PedidoRepository.ResumoFinanceiroProducao)Proxy.newProxyInstance(getClass().getClassLoader(),new Class[]{PedidoRepository.ResumoFinanceiroProducao.class},(x,y,z)->m.get(y.getName()));}
    private class Fake implements InvocationHandler {Producao entidade;PedidoRepository.ResumoFinanceiroProducao financeiro;boolean duplicada,duplicadaAtualizacao,excluiuProducao,alterouPedido;long total=1;ProducaoRepository pr;PedidoRepository ped;
        ProducaoService service(){ClassLoader c=getClass().getClassLoader();pr=(ProducaoRepository)Proxy.newProxyInstance(c,new Class[]{ProducaoRepository.class},this);ped=(PedidoRepository)Proxy.newProxyInstance(c,new Class[]{PedidoRepository.class},this);return new ProducaoService(pr,ped);}
        public Object invoke(Object proxy,Method m,Object[] a){return switch(m.getName()){case"existsByDataProducao"->duplicada;case"existsByDataProducaoAndIdNot"->duplicadaAtualizacao;case"saveAndFlush"->{entidade=(Producao)a[0];if(entidade.getId()==null)entidade.setId(1L);yield entidade;}case"findById"->Optional.ofNullable(entidade);case"delete"->{if(proxy==pr)excluiuProducao=true;else alterouPedido=true;yield null;}case"resumirFinanceiroProducao"->Optional.ofNullable(financeiro);case"buscarPorPeriodo"->new PageImpl<>(entidade==null?List.of():List.of(entidade),(Pageable)a[2],total);case"resumirFinanceiroProducoes"->financeiro==null?List.of():List.of(financeiro);default->null;};}}
}
