package br.com.sergio.gestaopedidos.controller.web;
import br.com.sergio.gestaopedidos.dto.composicao.*;import br.com.sergio.gestaopedidos.enums.TipoComponenteComposicao;import br.com.sergio.gestaopedidos.exception.BusinessException;import br.com.sergio.gestaopedidos.service.*;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.PageRequest;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.validation.BindingResult;import org.springframework.web.bind.annotation.*;import org.springframework.web.servlet.mvc.support.RedirectAttributes;import java.util.*;
@Controller@RequestMapping("/composicoes-produtos")@RequiredArgsConstructor
public class ComposicaoProdutoWebController{
 private final ComposicaoProdutoService service;private final ProdutoService produtos;
 @GetMapping public String listar(@RequestParam(defaultValue="")String produto,@RequestParam(required=false)Boolean ativa,@RequestParam(defaultValue="0")int pagina,Model model){var p=service.listar(produto,ativa,PageRequest.of(Math.max(0,pagina),10));model.addAttribute("paginaComposicoes",p);model.addAttribute("composicoes",p.getContent());model.addAttribute("produto",produto);model.addAttribute("ativa",ativa);return "composicoes-produtos/listar";}
 @GetMapping("/nova")public String nova(Model model){model.addAttribute("composicao",ComposicaoProdutoRequest.builder().ativa(true).itens(new ArrayList<>(List.of(ItemComposicaoProdutoRequest.builder().build()))).build());preparar(model,false,null);return "composicoes-produtos/formulario";}
 @PostMapping public String salvar(@Valid@ModelAttribute("composicao")ComposicaoProdutoRequest r,BindingResult result,Model model,RedirectAttributes redirect){if(!result.hasErrors())try{var c=service.salvar(r);redirect.addFlashAttribute("mensagemSucesso","Composição cadastrada com sucesso.");return "redirect:/composicoes-produtos/"+c.id();}catch(BusinessException e){result.reject("composicao.invalida",e.getMessage());}preparar(model,false,null);return "composicoes-produtos/formulario";}
 @GetMapping("/{id}")public String detalhes(@PathVariable Long id,Model model){model.addAttribute("composicao",service.buscar(id));return "composicoes-produtos/detalhes";}
 @GetMapping("/{id}/editar")public String editar(@PathVariable Long id,Model model){var c=service.buscar(id);model.addAttribute("composicao",ComposicaoProdutoRequest.builder().produtoComercialId(c.produtoComercialId()).ativa(c.ativa()).observacao(c.observacao()).itens(new ArrayList<>(c.itens().stream().map(i->ItemComposicaoProdutoRequest.builder().id(i.id()).tipoComponente(i.tipoComponente()).referenciaId(i.referenciaId()).quantidade(i.quantidade()).build()).toList())).build());model.addAttribute("itensAtuais",c.itens());preparar(model,true,id);return "composicoes-produtos/formulario";}
 @PostMapping("/{id}")public String atualizar(@PathVariable Long id,@Valid@ModelAttribute("composicao")ComposicaoProdutoRequest r,BindingResult result,Model model,RedirectAttributes redirect){if(!result.hasErrors())try{service.atualizar(id,r);redirect.addFlashAttribute("mensagemSucesso","Composição atualizada com sucesso.");return "redirect:/composicoes-produtos/"+id;}catch(BusinessException e){result.reject("composicao.invalida",e.getMessage());}preparar(model,true,id);return "composicoes-produtos/formulario";}
 @PostMapping("/{id}/ativar")public String ativar(@PathVariable Long id,RedirectAttributes r){service.ativar(id);r.addFlashAttribute("mensagemSucesso","Composição ativada.");return "redirect:/composicoes-produtos";}@PostMapping("/{id}/inativar")public String inativar(@PathVariable Long id,RedirectAttributes r){service.inativar(id);r.addFlashAttribute("mensagemSucesso","Composição inativada.");return "redirect:/composicoes-produtos";}@PostMapping("/{id}/excluir")public String excluir(@PathVariable Long id,RedirectAttributes r){service.excluir(id);r.addFlashAttribute("mensagemSucesso","Composição excluída.");return "redirect:/composicoes-produtos";}
 @GetMapping("/componentes")@ResponseBody public List<ComponenteComposicaoResponse> componentes(@RequestParam TipoComponenteComposicao tipo,@RequestParam(defaultValue="")String termo){return service.buscarComponentes(tipo,termo);}
 private void preparar(Model m,boolean edicao,Long id){m.addAttribute("titulo",edicao?"Editar composição":"Nova composição");m.addAttribute("modoEdicao",edicao);m.addAttribute("composicaoId",id);m.addAttribute("produtosComerciais",produtos.listarComerciaisAtivos());m.addAttribute("tiposComponente",TipoComponenteComposicao.values());}
}
