package br.com.sergio.gestaopedidos.service;
import br.com.sergio.gestaopedidos.dto.composicao.*;import br.com.sergio.gestaopedidos.entity.*;import br.com.sergio.gestaopedidos.enums.*;import br.com.sergio.gestaopedidos.exception.*;import br.com.sergio.gestaopedidos.repository.*;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.util.*;
@Service@RequiredArgsConstructor@Transactional
public class ComposicaoProdutoService{
 private final ComposicaoProdutoRepository repositorio;private final ProdutoRepository produtos;private final InsumoRepository insumos;private final SaldoEstoqueRepository saldos;
 @Transactional(readOnly=true)public Page<ComposicaoProdutoResponse> listar(String nome,Boolean ativa,Pageable p){return repositorio.listar(nome==null?"":nome.trim(),ativa,p).map(c->mapear(repositorio.buscarDetalhada(c.getId()).orElse(c)));}
 @Transactional(readOnly=true)public ComposicaoProdutoResponse buscar(Long id){return mapear(entidade(id));}
 public ComposicaoProdutoResponse salvar(ComposicaoProdutoRequest r){Produto p=produtoComercial(r.getProdutoComercialId(),true);if(repositorio.existsByProdutoComercialId(p.getId()))throw new BusinessException("Este produto já possui uma composição.");ComposicaoProduto c=ComposicaoProduto.builder().produtoComercial(p).ativa(r.getAtiva()==null?true:r.getAtiva()).observacao(texto(r.getObservacao())).build();montar(c,r.getItens());repositorio.save(c);return buscar(c.getId());}
 public ComposicaoProdutoResponse atualizar(Long id,ComposicaoProdutoRequest r){ComposicaoProduto c=entidade(id);if(!Objects.equals(c.getProdutoComercial().getId(),r.getProdutoComercialId()))throw new BusinessException("O produto comercial da composição não pode ser alterado.");produtoComercial(r.getProdutoComercialId(),false);c.getItens().clear();montar(c,r.getItens());c.setAtiva(r.getAtiva()==null?c.getAtiva():r.getAtiva());c.setObservacao(texto(r.getObservacao()));repositorio.save(c);return buscar(id);}
 public void ativar(Long id){ComposicaoProduto c=entidade(id);if(c.getItens().isEmpty())throw new BusinessException("A composição precisa possuir ao menos um componente.");c.setAtiva(true);}public void inativar(Long id){entidade(id).setAtiva(false);}public void excluir(Long id){repositorio.delete(entidade(id));}
 @Transactional(readOnly=true)public List<ComponenteComposicaoResponse> buscarComponentes(TipoComponenteComposicao tipo,String termo){String t=termo==null?"":termo.trim();if(tipo==TipoComponenteComposicao.INSUMO)return insumos.findTop20ByAtivoTrueAndNomeContainingIgnoreCaseOrderByNomeAsc(t).stream().map(i->componente(tipo,i.getId(),i.getNome(),i.getUnidadeMedida())).toList();if(tipo==TipoComponenteComposicao.PREPARACAO_PRODUZIDA)return produtos.findTop20ByTipoProdutoAndAtivoTrueAndNomeContainingIgnoreCaseOrderByNomeAsc(TipoProduto.PREPARACAO_PRODUZIDA,t).stream().map(p->componente(tipo,p.getId(),p.getNome(),unidade(p))).toList();throw new BusinessException("Selecione o tipo do componente.");}
 private void montar(ComposicaoProduto c,List<ItemComposicaoProdutoRequest> itens){if(itens==null||itens.isEmpty())throw new BusinessException("Adicione ao menos um componente.");Set<String> unicos=new HashSet<>();for(ItemComposicaoProdutoRequest r:itens){if(r==null||r.getTipoComponente()==null||r.getReferenciaId()==null)throw new BusinessException("Informe o tipo e o componente.");String chave=r.getTipoComponente()+":"+r.getReferenciaId();if(!unicos.add(chave))throw new BusinessException("O mesmo componente não pode ser repetido.");ItemComposicaoProduto i=ItemComposicaoProduto.builder().tipoComponente(r.getTipoComponente()).quantidade(quantidade(r.getQuantidade())).build();if(r.getTipoComponente()==TipoComponenteComposicao.INSUMO){Insumo x=insumos.findById(r.getReferenciaId()).orElseThrow(()->new ResourceNotFoundException("Insumo não encontrado."));if(!Boolean.TRUE.equals(x.getAtivo()))throw new BusinessException("O insumo "+x.getNome()+" está inativo.");i.setInsumo(x);i.setNomeHistorico(x.getNome());i.setUnidadeHistorica(x.getUnidadeMedida());validarPrecisao(i.getQuantidade(),x.getUnidadeMedida());}else{Produto x=produtos.findById(r.getReferenciaId()).orElseThrow(()->new ResourceNotFoundException("Preparação não encontrada."));if(x.getTipoProduto()!=TipoProduto.PREPARACAO_PRODUZIDA||!Boolean.TRUE.equals(x.getAtivo()))throw new BusinessException("Somente preparações produzidas ativas podem compor o produto.");i.setPreparacao(x);i.setNomeHistorico(x.getNome());i.setUnidadeHistorica(unidade(x));validarPrecisao(i.getQuantidade(),i.getUnidadeHistorica());}c.adicionarItem(i);}}
 private ComposicaoProdutoResponse mapear(ComposicaoProduto c){List<ItemComposicaoProdutoResponse> itens=c.getItens().stream().map(i->{Long id=i.getInsumo()!=null?i.getInsumo().getId():i.getPreparacao().getId();TipoItemEstoque tipo=i.getInsumo()!=null?TipoItemEstoque.INSUMO:TipoItemEstoque.PREPARACAO_PRODUZIDA;BigDecimal medio=saldos.buscarSaldo(tipo,id).map(SaldoEstoque::getCustoMedioAtual).orElse(BigDecimal.ZERO.setScale(6));return ItemComposicaoProdutoResponse.builder().id(i.getId()).tipoComponente(i.getTipoComponente()).referenciaId(id).nome(i.getNomeHistorico()).unidade(i.getUnidadeHistorica()).quantidade(i.getQuantidade()).custoMedio(medio).custoEstimado(i.getQuantidade().multiply(medio).setScale(2,RoundingMode.HALF_UP)).build();}).toList();BigDecimal total=itens.stream().map(ItemComposicaoProdutoResponse::custoEstimado).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2,RoundingMode.HALF_UP);return ComposicaoProdutoResponse.builder().id(c.getId()).produtoComercialId(c.getProdutoComercial().getId()).produtoComercialNome(c.getProdutoComercial().getNome()).ativa(c.getAtiva()).observacao(c.getObservacao()).criadoEm(c.getCriadoEm()).atualizadoEm(c.getAtualizadoEm()).itens(itens).custoEstimadoTotal(total).build();}
 private ComponenteComposicaoResponse componente(TipoComponenteComposicao tipo,Long id,String nome,UnidadeMedida unidade){TipoItemEstoque categoria=tipo==TipoComponenteComposicao.INSUMO?TipoItemEstoque.INSUMO:TipoItemEstoque.PREPARACAO_PRODUZIDA;BigDecimal custo=saldos.buscarSaldo(categoria,id).map(SaldoEstoque::getCustoMedioAtual).orElse(BigDecimal.ZERO.setScale(6));return ComponenteComposicaoResponse.builder().tipo(tipo).id(id).nome(nome).unidade(unidade).custoMedio(custo).build();}
 private Produto produtoComercial(Long id,boolean ativo){Produto p=produtos.findById(id).orElseThrow(()->new ResourceNotFoundException("Produto não encontrado."));if(p.getTipoProduto()!=TipoProduto.PRODUTO_COMERCIAL)throw new BusinessException("Somente Produto de venda pode possuir composição comercial.");if(ativo&&!Boolean.TRUE.equals(p.getAtivo()))throw new BusinessException("O produto comercial está inativo.");return p;}
 private ComposicaoProduto entidade(Long id){return repositorio.buscarDetalhada(id).orElseThrow(()->new ResourceNotFoundException("Composição não encontrada."));}private BigDecimal quantidade(BigDecimal q){if(q==null||q.signum()<=0||q.stripTrailingZeros().scale()>3)throw new BusinessException("Quantidade deve ser maior que zero e ter no máximo três casas decimais.");return q.setScale(3,RoundingMode.UNNECESSARY);}private void validarPrecisao(BigDecimal q,UnidadeMedida u){if(u==UnidadeMedida.UNIDADE&&q.stripTrailingZeros().scale()>0)throw new BusinessException("Quantidade em unidade deve ser inteira.");}private UnidadeMedida unidade(Produto p){return p.getUnidadeVenda()==UnidadeVenda.UNIDADE?UnidadeMedida.UNIDADE:UnidadeMedida.QUILOGRAMA;}private String texto(String s){return s==null||s.trim().isEmpty()?null:s.trim();}
}
