package br.com.sergio.gestaopedidos.service;
import br.com.sergio.gestaopedidos.dto.estoque.*;import br.com.sergio.gestaopedidos.entity.*;import br.com.sergio.gestaopedidos.enums.*;import br.com.sergio.gestaopedidos.exception.*;import br.com.sergio.gestaopedidos.repository.*;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.*;import java.util.*;
@Service@RequiredArgsConstructor@Transactional public class EstoqueService{
 private final EstoqueInsumoRepository estoqueRepository;private final MovimentacaoEstoqueRepository movimentoRepository;private final ItemCompraInsumoRepository itemRepository;
 public void processarCompra(CompraInsumo compra){if(compra.getStatus()==StatusCompraInsumo.ESTORNADA)return;for(ItemCompraInsumo item:compra.getItens())if(!movimentoRepository.existsByItemCompraInsumoIdAndTipo(item.getId(),TipoMovimentacaoEstoque.ENTRADA_COMPRA))registrarEntrada(item.getInsumo(),item.getQuantidade(),item.getValorTotalItem(),item.getCustoUnitario(),TipoMovimentacaoEstoque.ENTRADA_COMPRA,compra.getDataCompra().atStartOfDay(),"Compra de insumos #"+compra.getId(),item,null);}
 public int migrarComprasAntigas(){int total=0;while(true){Slice<ItemCompraInsumo>s=itemRepository.buscarSemMovimento(TipoMovimentacaoEstoque.ENTRADA_COMPRA,PageRequest.of(0,500));if(s.isEmpty())break;for(var i:s){registrarEntrada(i.getInsumo(),i.getQuantidade(),i.getValorTotalItem(),i.getCustoUnitario(),TipoMovimentacaoEstoque.ENTRADA_COMPRA,i.getCompra().getDataCompra().atStartOfDay(),"Migração da compra #"+i.getCompra().getId(),i,null);total++;}}return total;}
 public void registrarEntradaManual(EntradaEstoqueRequest r){Insumo i=insumoAtivo(r.getInsumoId());BigDecimal q=quantidade(r.getQuantidade(),i.getUnidadeMedida()),v=valorPositivo(r.getValorTotal());registrarEntrada(i,q,v,v.divide(q,6,RoundingMode.HALF_UP),TipoMovimentacaoEstoque.ENTRADA_AJUSTE,r.getDataMovimentacao(),normalizar(r.getObservacao()),null,null);}
 public void registrarSaidaManual(SaidaEstoqueRequest r){if(!Set.of(TipoMovimentacaoEstoque.SAIDA_CONSUMO_MANUAL,TipoMovimentacaoEstoque.SAIDA_PERDA,TipoMovimentacaoEstoque.SAIDA_AJUSTE).contains(r.getTipo()))throw new BusinessException("Tipo de saída inválido.");Insumo i=insumoAtivo(r.getInsumoId());BigDecimal q=quantidade(r.getQuantidade(),i.getUnidadeMedida());EstoqueInsumo e=bloquearSaldo(i);if(e.getQuantidadeAtual().compareTo(q)<0)throw new BusinessException("Estoque insuficiente. Disponível: "+e.getQuantidadeAtual().stripTrailingZeros().toPlainString()+" "+i.getUnidadeMedida().getSimbolo()+".");BigDecimal custo=e.getCustoMedioAtual(),valor=q.multiply(custo).setScale(2,RoundingMode.HALF_UP);movimentoRepository.save(movimento(i,r.getDataMovimentacao(),r.getTipo(),q,valor,custo,normalizar(r.getObservacao()),null,null));e.setQuantidadeAtual(e.getQuantidadeAtual().subtract(q).setScale(3));e.setValorTotalEstoque(e.getValorTotalEstoque().subtract(valor).max(BigDecimal.ZERO).setScale(2));if(e.getQuantidadeAtual().signum()==0){e.setCustoMedioAtual(zero6());e.setValorTotalEstoque(zero2());}estoqueRepository.save(e);}
 public void estornarCompra(CompraInsumo compra){if(compra.getStatus()==StatusCompraInsumo.ESTORNADA)throw new BusinessException("Esta compra já foi estornada.");List<MovimentacaoEstoque> origens=movimentoRepository.findByItemCompraInsumoCompraIdAndTipoOrderByIdAsc(compra.getId(),TipoMovimentacaoEstoque.ENTRADA_COMPRA);if(origens.isEmpty())throw new BusinessException("A compra ainda não possui entradas de estoque.");for(var origem:origens){EstoqueInsumo e=bloquearSaldo(origem.getInsumo());if(e.getQuantidadeAtual().compareTo(origem.getQuantidade())<0||e.getValorTotalEstoque().compareTo(origem.getValorTotal())<0)throw new BusinessException("Não é possível estornar: o estoque atual não comporta a reversão desta compra.");movimentoRepository.save(movimento(origem.getInsumo(),LocalDateTime.now(),TipoMovimentacaoEstoque.ESTORNO_ENTRADA,origem.getQuantidade(),origem.getValorTotal(),origem.getCustoUnitario(),"Estorno da compra #"+compra.getId(),origem.getItemCompraInsumo(),origem));e.setQuantidadeAtual(e.getQuantidadeAtual().subtract(origem.getQuantidade()).setScale(3));e.setValorTotalEstoque(e.getValorTotalEstoque().subtract(origem.getValorTotal()).setScale(2));recalcularMedio(e);estoqueRepository.save(e);}compra.setStatus(StatusCompraInsumo.ESTORNADA);}
 public boolean compraMovimentada(Long id){return !movimentoRepository.findByItemCompraInsumoCompraIdAndTipoOrderByIdAsc(id,TipoMovimentacaoEstoque.ENTRADA_COMPRA).isEmpty();}
 @Transactional(readOnly=true)public Page<EstoqueInsumoResponse>listar(String nome,String situacao,Boolean ativo,Pageable p){return estoqueRepository.listar(limpar(nome),limpar(situacao),ativo,p).map(this::mapearSaldo);}
 @Transactional(readOnly=true)public EstoqueIndicadoresResponse indicadores(){LocalDate h=LocalDate.now();return EstoqueIndicadoresResponse.builder().insumosComSaldo(estoqueRepository.countByQuantidadeAtualGreaterThan(BigDecimal.ZERO)).abaixoDoMinimo(estoqueRepository.contarAbaixoMinimo()).valorEstimado(moeda(estoqueRepository.somarValorEstoque())).movimentacoesHoje(movimentoRepository.countByDataMovimentacaoBetween(h.atStartOfDay(),h.plusDays(1).atStartOfDay())).build();}
 @Transactional(readOnly=true)public Page<MovimentacaoEstoqueResponse>movimentacoes(LocalDate inicio,LocalDate fim,Long insumo,TipoMovimentacaoEstoque tipo,Long compra,Pageable p){return movimentoRepository.listar(inicio==null?null:inicio.atStartOfDay(),fim==null?null:fim.plusDays(1).atStartOfDay().minusNanos(1),insumo,tipo,compra,p).map(this::mapearMovimento);}
 @Transactional(readOnly=true)public EstoqueInsumoDetalhesResponse detalhes(Long id){Insumo i=estoqueRepository.buscarInsumo(id).orElseThrow(()->new ResourceNotFoundException("Insumo não encontrado."));EstoqueInsumo e=estoqueRepository.buscarSaldo(id).orElse(EstoqueInsumo.builder().insumo(i).build());EstoqueInsumoResponse saldo=mapear(i,e);return EstoqueInsumoDetalhesResponse.builder().estoque(saldo).movimentacoes(movimentoRepository.findTop20ByInsumoIdOrderByDataMovimentacaoDescIdDesc(id).stream().map(this::mapearMovimento).toList()).build();}
 private void registrarEntrada(Insumo i,BigDecimal q,BigDecimal v,BigDecimal custo,TipoMovimentacaoEstoque tipo,LocalDateTime data,String obs,ItemCompraInsumo item,MovimentacaoEstoque origem){q=quantidade(q,i.getUnidadeMedida());v=moeda(v);EstoqueInsumo e=bloquearSaldo(i);BigDecimal novaQ=e.getQuantidadeAtual().add(q).setScale(3);BigDecimal novoV=e.getValorTotalEstoque().add(v).setScale(2);e.setQuantidadeAtual(novaQ);e.setValorTotalEstoque(novoV);e.setCustoMedioAtual(novoV.divide(novaQ,6,RoundingMode.HALF_UP));movimentoRepository.save(movimento(i,data,tipo,q,v,custo.setScale(6,RoundingMode.HALF_UP),obs,item,origem));estoqueRepository.save(e);}
 private EstoqueInsumo bloquearSaldo(Insumo i){estoqueRepository.bloquearInsumo(i.getId()).orElseThrow(()->new ResourceNotFoundException("Insumo não encontrado."));return estoqueRepository.findByInsumoId(i.getId()).orElseGet(()->EstoqueInsumo.builder().insumo(i).build());}
 private Insumo insumoAtivo(Long id){Insumo i=estoqueRepository.bloquearInsumo(id).orElseThrow(()->new ResourceNotFoundException("Insumo não encontrado."));if(!Boolean.TRUE.equals(i.getAtivo()))throw new BusinessException("Este insumo não está disponível para novas movimentações.");return i;}
 private MovimentacaoEstoque movimento(Insumo i,LocalDateTime d,TipoMovimentacaoEstoque t,BigDecimal q,BigDecimal v,BigDecimal c,String o,ItemCompraInsumo item,MovimentacaoEstoque origem){return MovimentacaoEstoque.builder().insumo(i).dataMovimentacao(d==null?LocalDateTime.now():d).tipo(t).quantidade(q).unidadeMedida(i.getUnidadeMedida()).valorTotal(v).custoUnitario(c).observacao(o).itemCompraInsumo(item).movimentacaoOrigem(origem).build();}
 private void recalcularMedio(EstoqueInsumo e){if(e.getQuantidadeAtual().signum()==0){e.setCustoMedioAtual(zero6());e.setValorTotalEstoque(zero2());}else e.setCustoMedioAtual(e.getValorTotalEstoque().divide(e.getQuantidadeAtual(),6,RoundingMode.HALF_UP));}
 private BigDecimal quantidade(BigDecimal q,UnidadeMedida u){if(q==null||q.signum()<=0)throw new BusinessException("Quantidade deve ser maior que zero.");if(q.stripTrailingZeros().scale()>3)throw new BusinessException("Quantidade deve ter no máximo três casas decimais.");if(u==UnidadeMedida.UNIDADE&&q.stripTrailingZeros().scale()>0)throw new BusinessException("Quantidade em unidade deve ser inteira.");return q.setScale(3,RoundingMode.UNNECESSARY);}private BigDecimal valorPositivo(BigDecimal v){if(v==null||v.signum()<=0)throw new BusinessException("Valor deve ser maior que zero.");return moeda(v);}private BigDecimal moeda(BigDecimal v){return(v==null?BigDecimal.ZERO:v).setScale(2,RoundingMode.HALF_UP);}private BigDecimal zero2(){return BigDecimal.ZERO.setScale(2);}private BigDecimal zero6(){return BigDecimal.ZERO.setScale(6);}private String normalizar(String s){String v=limpar(s);return v.isEmpty()?null:v;}private String limpar(String s){return s==null?"":s.trim();}
 private EstoqueInsumoResponse mapearSaldo(EstoqueInsumoRepository.Saldo s){return montar(s.getInsumoId(),s.getInsumoNome(),s.getUnidadeMedida(),s.getAtivo(),s.getQuantidadeAtual(),s.getEstoqueMinimo(),s.getCustoMedioAtual(),s.getValorTotalEstoque(),s.getAtualizadoEm());}private EstoqueInsumoResponse mapear(Insumo i,EstoqueInsumo e){return montar(i.getId(),i.getNome(),i.getUnidadeMedida(),i.getAtivo(),e.getQuantidadeAtual(),i.getEstoqueMinimo(),e.getCustoMedioAtual(),e.getValorTotalEstoque(),e.getAtualizadoEm());}private EstoqueInsumoResponse montar(Long id,String nome,UnidadeMedida u,Boolean ativo,BigDecimal q,BigDecimal min,BigDecimal custo,BigDecimal valor,LocalDateTime ultima){q=q==null?BigDecimal.ZERO:q;min=min==null?BigDecimal.ZERO:min;boolean baixo=min.signum()>0&&q.compareTo(min)<=0;String sit=q.signum()==0?"Sem estoque":baixo?"Estoque baixo":min.signum()==0?"Sem mínimo configurado":"Normal";return EstoqueInsumoResponse.builder().insumoId(id).insumoNome(nome).unidadeMedida(u).ativo(ativo).estoqueAtual(q).estoqueMinimo(min).abaixoDoMinimo(baixo).situacao(sit).custoMedioAtual(custo==null?zero6():custo).valorEstimadoEstoque(valor==null?zero2():valor).ultimaMovimentacao(ultima).build();}
 private MovimentacaoEstoqueResponse mapearMovimento(MovimentacaoEstoque m){String origem=m.getMovimentacaoOrigem()!=null?"Estorno #"+m.getMovimentacaoOrigem().getId():m.getItemCompraInsumo()!=null?"Compra #"+m.getItemCompraInsumo().getCompra().getId():"Manual";return MovimentacaoEstoqueResponse.builder().id(m.getId()).insumoId(m.getInsumo().getId()).insumoNome(m.getInsumo().getNome()).dataMovimentacao(m.getDataMovimentacao()).tipo(m.getTipo()).quantidade(m.getQuantidade()).unidadeMedida(m.getUnidadeMedida()).valorTotal(m.getValorTotal()).custoUnitario(m.getCustoUnitario()).origem(origem).observacao(m.getObservacao()).build();}
}
